# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestcase():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testcase(self):
        self.driver.get(
            "https://www.zomato.com/bangalore/delivery?utm_source=google&utm_medium=cpc&utm_campaign=Gsearch_P-MWeb_O-NA_C-Brand_A-NewUser_SC-Generic_L-PanIndia&utm_term=zomato&gclid=CjwKCAiAl-6PBhBCEiwAc2GOVNPq7tDFVvN1FwY-pVCYZ_de3RA7DKunvW_4mpMeV23gzIid8T6-9RoCf6kQAvD_BwE")
        self.driver.set_window_size(1050, 708)
        self.driver.find_element(By.CSS_SELECTOR, ".sc-cqpYsc").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sc-cqpYsc").send_keys("mutton ")
        self.driver.find_element(By.CSS_SELECTOR, ".sc-jdfcpN:nth-child(1) > .sc-kNBZmU").click()
        self.driver.find_element(By.CSS_SELECTOR, "#TabLink__1 > .sc-hQrNYi").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".sc-1mo3ldo-0:nth-child(8) .sc-sPYgB:nth-child(1) .sc-dTLGrV .sc-s1isp7-5").click()
        self.driver.find_element(By.LINK_TEXT, "Sign up").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fEhkvd").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fEhkvd").send_keys("gowtham")
        self.driver.find_element(By.CSS_SELECTOR, ".fEhkvd").send_keys("gowtham.kaja@gmail.com")
        self.driver.find_element(By.CSS_SELECTOR, ".sc-1o2pknd-0:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sc-1kx5g6g-1:nth-child(6) > .sc-1kx5g6g-2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fEhkvd").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sc-13lc47p-0:nth-child(68) .sc-rbbb40-0").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fNAGoy").click()

